minimal_mistakes_skin: "sunrise" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
title: "Abhi's Personal Website"
name: "Abhilash Venkatesh"
description: "Abhi's collection of blogs, projects,  portfolio, conference, meetup talks."
url: "https://abhi4578.github.io"
repository: "abhi4578/abhi4578.github.io"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Calcutta

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

lunr:
  search_within_pages: true
author:
  name     : "Abhilash Venkatesh"
  avatar   : "/assets/images/bio.jpg"
  bio      : "Currently a grad student at OMSCS. I love Linux, FOSS and systems!"
  location : "Bengaluru, India"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/abhi4578"
    - label: "Linkedin"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/abhi5782-/"
    - label: "Google Scholar"
      icon: "fa-brands fa-google-scholar"
      url: "https://scholar.google.com/citations?user=8K_E_9EAAAAJ&hl=en"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://noc.social/@urnbhai"
    - label: "X"
      icon: "fa-brands fa-square-x-twitter"
      url: "https://X.com/Abhi00434"
    - label: "Goodreads"
      icon: "fa-solid fa-goodreads"
      url: "https://goodreads.com/urnbhai"
include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
footer_scripts:
  - /assets/js/quotes.js